services:
  app1_blue:
    build: ./App1
    container_name: app1_blue
    restart: unless-stopped
    networks:
      - webnet

  app2_blue:
    build: ./App2
    container_name: app2_blue
    restart: unless-stopped
    networks:
      - webnet

  nginx-proxy:
    build: ./nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    depends_on:
      - app1_blue
      - app2_blue
    networks:
      - webnet

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM; while :; do
      certbot renew --webroot -w /var/www/certbot --quiet --deploy-hook 'nginx -s reload';
      sleep 12h & wait $${!}; done"

networks:
  webnet:
    driver: bridge

volumes:
  certbot-etc:
  certbot-webroot:
