resolver 127.0.0.11 valid=10s;

# App1 : redirection HTTP vers HTTPS 
server {
    listen 80;
    server_name kossiapp.duckdns.org;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 301 https://$host$request_uri; }
}

#  App2 : redirection HTTP vers HTTPS 
server {
    listen 80;
    server_name kossiapp2.duckdns.org;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 301 https://$host$request_uri; }
}

# App1 en HTTPS
server {
    listen 443 ssl;
    server_name kossiapp.duckdns.org;

    ssl_certificate     /etc/letsencrypt/live/kossiapp.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kossiapp.duckdns.org/privkey.pem;

    include /etc/nginx/conf.d/upstreams/app1_active.conf;

    location / {
        proxy_pass http://$app1_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# App2 en HTTPS 
server {
    listen 443 ssl;
    server_name kossiapp2.duckdns.org;

    ssl_certificate     /etc/letsencrypt/live/kossiapp.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kossiapp.duckdns.org/privkey.pem;

    include /etc/nginx/conf.d/upstreams/app2_active.conf;

    location / {
        proxy_pass http://$app2_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
